Repository LetrazApp/letraz-server, pull requests merged in 2025-08, with the labels that each got.

#131 LTB-46 | logic: Callback system for ScrapeJob RPC method call
  CORE/migrations/0001_initial.py
  CORE/models.py
  JOB/admin.py
  JOB/grpc/JOB.proto
  JOB/grpc/JOB_pb2.py
  JOB/grpc/JOB_pb2_grpc.py
  JOB/migrations/0001_initial.py
  JOB/models.py
  JOB/proto_serializers.py
  JOB/proto_serialzers.py
  JOB/serializers.py
  JOB/services.py
  PROFILE/migrations/0001_initial.py
  RESUME/admin.py
  RESUME/api_views.py
  RESUME/migrations/0001_initial.py
  RESUME/models.py
  RESUME/serializers.py
  RESUME/utils.py
  letraz_server/handlers.py
Labels: Logic, Feature

#139 LTB-58 | logic: Strategy and functionality to call screenshotting service for resume thumbnail generation
  CORE/migrations/0001_initial.py
  JOB/migrations/0001_initial.py
  PROFILE/migrations/0001_initial.py
  RESUME/admin.py
  RESUME/api_views.py
  RESUME/apps.py
  RESUME/migrations/0001_initial.py
  RESUME/models.py
  RESUME/services.py
  RESUME/signals.py
  RESUME/utils.py
  letraz_server/settings.py
Labels: Logic, Feature

#142 LTB-91 | bug: "SSL connection already closed" error in TailorResume callback's skill populating thread
  RESUME/models.py
  RESUME/services.py
Labels: bug

#143 LTB-81 | logic: Callback system for GenerateScreenshot RPC method call
  RESUME/grpc/RESUME.proto
  RESUME/grpc/RESUME_pb2.py
  RESUME/grpc/RESUME_pb2_grpc.py
  RESUME/migrations/0002_resume_thumbnail.py
  RESUME/models.py
  RESUME/proto_serializers.py
  RESUME/serializers.py
  RESUME/services.py
  letraz_server/handlers.py
Labels: Logic, Feature, Core, API

#149 LTB-95 | bug: GenerateScreenshotCallBackService is redeclared, due to which re-indexation after thumbnail generation fails
  RESUME/services.py
Labels: bug, Logic, Improvement

#154 LTB-98 | bug: Tailoring resumes process fails with error if job with the same URL exists
  RESUME/api_views.py
Labels: bug, Logic, API

#155 LTB-97 | bug: Some LinkedIn URLs are being rejected while parsing on letraz-utils
  RESUME/api_views.py
Labels: bug, Logic, Improvement

#157 LTB-99 | bug: Resume section reordering failing due to rapid thumbnail generation
  RESUME/api_views.py
Labels: bug, Logic

#159 LTB-100 | bug: Resume section reordering and adding new education fails with error
  RESUME/api_views.py
  RESUME/serializers.py
  RESUME/signals.py
  RESUME/utils.py
Labels: bug, Logic, API

#168 LTB-103 | api: API endpoint for replacing an entire resume object with a new object
  RESUME/api_views.py
  RESUME/serializers.py
Labels: Logic, Feature, API

#172 LTB-18 | fix: Schema inconsistencies in auto generated documentation
  CORE/admin_api_views.py
  CORE/api_views.py
  CORE/serializers.py
  JOB/api_views.py
  PROFILE/api_views.py
  RESUME/admin_api_views.py
  RESUME/api_views.py
  RESUME/serializers.py
  letraz_server/settings.py
  schema.yml
Labels: bug, Improvement

#174 LTB-94 | api: API endpoint for accepting resume export request
  RESUME/admin.py
  RESUME/api_views.py
  RESUME/doc_only_serializers.py
  letraz_server/conf/grpc_client/utils/letraz-utils.proto
  letraz_server/conf/grpc_client/utils/letraz_utils_pb2.py
  letraz_server/conf/grpc_client/utils/letraz_utils_pb2_grpc.py
  schema.yml
Labels: Logic, Feature, API
